version: '3.8'

services:
  music-tag-enhance:
    container_name: music-tag-enhance
    build: .
    stdin_open: true
    tty: true
    network_mode: host
    volumes:
      - ./app:/app
      # 可以挂载sqlite数据库文件
      #- /path/to/your/sqlite:/data/sqlite
    environment:
      - 'TZ=Asia/Shanghai'
      - POSTGRESQL_HOST=localhost
      - POSTGRESQL_PORT=5432
      - POSTGRESQL_DBNAME=your_db
      - POSTGRESQL_USER=your_user
      - POSTGRESQL_PASSWORD=your_password
