version: '3.8'

services:
  music-tag-enhance:
    container_name: music-tag-enhance
    build:
      context: .
    args:
      - http_proxy=http://127.0.0.1:10809
      - https_proxy=http://127.0.0.1:10809
    stdin_open: true
    tty: true
    network_mode: host
    volumes:
      - ./app:/app
    environment:
      - TZ=Asia/Shanghai
      - POSTGRESQL_HOST=103.30.78.190
      - POSTGRESQL_PORT=5432
      - POSTGRESQL_DBNAME=n8n
      - POSTGRESQL_USER=root
      - POSTGRESQL_PASSWORD=#hup7VA03iY^RN9
      - SQLITE_DB_PATH=../docker/dockerfile_work/nas/music/MusicTagWeb/config
